### ISSUE TITLE
npm install errors out

### ISSUE THREAD

**Issue by boydkelly** [yagebu/tree-sitter-beancount#1]
Hi,

Getting this error on Fedora 34.   Any suggestions?

[bkelly@toolbox ~]$ npm version
{ bkelly: '1.0.0',
  npm: '6.14.10',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.9.3',
  icu: '64.2',
  modules: '64',
  napi: '7',
  nghttp2: '1.41.0',
  node: '10.23.0',
  openssl: '1.1.1g',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.34.2',
  v8: '6.8.275.32-node.59',
  zlib: '1.2.11' }

[bkelly@toolbox ~]$ npm install tree-sitter-beancount --save

> tree-sitter-beancount@2.0.0 install /var/home/bkelly/node_modules/tree-sitter-beancount
> node-gyp rebuild

make: Entering directory '/var/home/bkelly/node_modules/tree-sitter-beancount/build'
  CC(target) Release/obj.target/tree_sitter_beancount_binding/src/parser.o
In file included from ../src/parser.c:1:
../src/parser.c: In function ‘ts_lex_keywords’:
../src/tree_sitter/parser.h:131:8: warning: variable ‘eof’ set but not used [-Wunused-but-set-variable]
  131 |   bool eof = false;             \
      |        ^~~
../src/parser.c:2964:3: note: in expansion of macro ‘START_LEXER’
 2964 |   START_LEXER();
      |   ^~~~~~~~~~~
  CXX(target) Release/obj.target/tree_sitter_beancount_binding/src/binding.o
make: g++: No such file or directory
make: *** [tree_sitter_beancount_binding.target.mk:108: Release/obj.target/tree_sitter_beancount_binding/src/binding.o] Error 127
make: Leaving directory '/var/home/bkelly/node_modules/tree-sitter-beancount/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/var/home/bkelly/.nvm/versions/node/v10.23.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.11.3-300.fc34.x86_64
gyp ERR! command "/var/home/bkelly/.nvm/versions/node/v10.23.0/bin/node" "/var/home/bkelly/.nvm/versions/node/v10.23.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/home/bkelly/node_modules/tree-sitter-beancount
gyp ERR! node -v v10.23.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN bkelly@1.0.0 No description
npm WARN bkelly@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-beancount@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-beancount@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/home/bkelly/.npm/_logs/2021-03-23T09_53_10_505Z-debug.log
[bkelly@toolbox ~]$

**Comment by yagebu** [comment]
You got the wrong repo, this one is not available on npm

**Comment by boydkelly** [comment]
oh ok.   Do you have any usage example for this?

**Comment by yagebu** [comment]
You can use it like any other tree-sitter grammar, apart from that it doesn't have any specific use cases.
